version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: meu_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: meu_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_DEFAULT_PASS}
    ports:
      - "8081:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
