/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 optimized-room.glb
*/

import React, { useMemo, useRef } from "react"
import { useGLTF, useTexture } from "@react-three/drei"
import { EffectComposer, SelectiveBloom } from "@react-three/postprocessing"
import { BlendFunction } from "postprocessing"
import * as THREE from "three"

export function Room(props) {
  const { nodes, materials } = useGLTF("/models/optimized-room.glb")
  const screensRef = useRef()

  /* ================= TEXTURES ================= */
  const matcapTexture = useTexture("/images/textures/mat1.png")

  /* ================= COLORS ================= */
  const accentColor = useMemo(() => {
    const c = new THREE.Color("#2a6f97")
    c.offsetHSL(0.02, 0, 0)
    return c
  }, [])

  /* ================= MATERIALS ================= */
  const bodyMaterial = useMemo(
    () =>
      new THREE.MeshPhongMaterial({
        map: matcapTexture,
      }),
    [matcapTexture]
  )

  const curtainMaterial = useMemo(
    () =>
      new THREE.MeshPhongMaterial({
        color: "#5a1e24",
      }),
    []
  )

  const tableMaterial = useMemo(
    () =>
      new THREE.MeshStandardMaterial({
        color: "#2f2a26",
        roughness: 0.65,
        metalness: 0.05,
      }),
    []
  )

  const chairMaterial = useMemo(
    () =>
      new THREE.MeshStandardMaterial({
        color: "#20232b",
        roughness: 0.7,
      }),
    []
  )

  const pillowMaterial = useMemo(
    () =>
      new THREE.MeshPhongMaterial({
        color: accentColor,
        shininess: 25,
      }),
    [accentColor]
  )

  const detailAccentMaterial = useMemo(
    () =>
      new THREE.MeshStandardMaterial({
        color: "#c76d2b",
        roughness: 0.45,
        metalness: 0.2,
      }),
    []
  )

  const radiatorMaterial = useMemo(
    () =>
      new THREE.MeshStandardMaterial({
        color: "#e6e6e6",
        roughness: 0.6,
      }),
    []
  )

  const compMaterial = useMemo(
    () =>
      new THREE.MeshStandardMaterial({
        color: "#dcdfe3",
        roughness: 0.35,
        metalness: 0.15,
      }),
    []
  )

  /* ================= COMMON PROPS ================= */
  const meshProps = {
    castShadow: true,
    receiveShadow: true,
  }

  return (
    <group {...props} dispose={null}>
      {/* ================= POSTPROCESS ================= */}
      <EffectComposer>
        <SelectiveBloom
          selection={screensRef}
          intensity={1}
          luminanceThreshold={0.25}
          luminanceSmoothing={0.85}
          blendFunction={BlendFunction.ADD}
        />
      </EffectComposer>

      {/* ================= GEOMETRY ================= */}
      <mesh
        {...meshProps}
        geometry={nodes._________6_blinn1_0.geometry}
        material={curtainMaterial}
      />
      <mesh
        {...meshProps}
        geometry={nodes.body1_blinn1_0.geometry}
        material={bodyMaterial}
      />
      <mesh
        {...meshProps}
        geometry={nodes.cabin_blinn1_0.geometry}
        material={tableMaterial}
      />
      <mesh
        {...meshProps}
        geometry={nodes.chair_body_blinn1_0.geometry}
        material={chairMaterial}
      />
      <mesh
        {...meshProps}
        geometry={nodes.comp_blinn1_0.geometry}
        material={compMaterial}
      />

      {/* SCREENS */}
      <mesh
        {...meshProps}
        ref={screensRef}
        geometry={nodes.emis_lambert1_0.geometry}
        material={materials.lambert1}
      />

      {/* GENERIC BLINN OBJECTS */}
      {[
        nodes.handls_blinn1_0,
        nodes.keyboard_blinn1_0,
        nodes.kovrik_blinn1_0,
        nodes.lamp_bl_blinn1_0,
        nodes.lamp_white_blinn1_0,
        nodes.miuse_blinn1_0,
        nodes.monitor2_blinn1_0,
        nodes.monitor3_blinn1_0,
        nodes.pCylinder5_blinn1_0,
        nodes.polySurface53_blinn1_0,
        nodes.railing_blinn1_0,
        nodes.red_bttns_blinn1_0,
        nodes.red_vac_blinn1_0,
        nodes.stylus_blinn1_0,
        nodes.tablet_blinn1_0,
        nodes.triangle_blinn1_0,
        nodes.vac_black_blinn1_0,
        nodes.vacuum1_blinn1_0,
        nodes.vacuumgrey_blinn1_0,
        nodes.vires_blinn1_0,
      ].map((node, i) => (
        <mesh
          key={i}
          {...meshProps}
          geometry={node.geometry}
          material={materials.blinn1}
        />
      ))}

      {/* PILLOWS */}
      <mesh
        {...meshProps}
        geometry={nodes.pillows_blinn1_0.geometry}
        material={pillowMaterial}
      />

      {/* RADIATOR */}
      <mesh
        {...meshProps}
        geometry={nodes.radiator_blinn1_0.geometry}
        material={radiatorMaterial}
      />
      <mesh
        {...meshProps}
        geometry={nodes.radiator_blinn1_0001.geometry}
        material={detailAccentMaterial}
      />

      {/* TABLE / WINDOW */}
      <mesh
        {...meshProps}
        geometry={nodes.table_blinn1_0.geometry}
        material={tableMaterial}
      />
      <mesh
        {...meshProps}
        geometry={nodes.window_blinn1_0.geometry}
        material={tableMaterial}
      />
      <mesh
        {...meshProps}
        geometry={nodes.window4_phong1_0.geometry}
        material={materials.phong1}
      />
    </group>
  )
}

useGLTF.preload("/models/optimized-room.glb")
