jwt:
  public:
    key: ${JWT_PUBLIC_KEY_PATH}
    token-expiration-minutes: ${ACCESS_TOKEN_EXPIRATION_MINUTES}
  private:
    key: ${JWT_PRIVATE_KEY_PATH}
  refresh:
    token-expiration-minutes: ${REFRESH_TOKEN_EXPIRATION_MINUTES}

spring:
  application:
    name: backend

  output:
    ansi:
      enabled: always

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver